language: php

php:
    - "7.3"

cache:
    directories:
        - $HOME/.composer/cache/files

before_script:
    - phpenv config-add travis.php.ini
    - phpenv config-rm xdebug.ini || echo "xdebug not available for PHP $TRAVIS_PHP_VERSION"
    - composer install --no-interaction --no-scripts --ignore-platform-reqs

script:
    - ./vendor/bin/phpspec run
    - ./vendor/bin/php-cs-fixer fix --diff --dry-run --config=.php_cs.php
